name:
  .trash: ï‡¸
  .cargo: î¨
  .emacs.d: î¹
  a.out: ï’‰
extension:
  go: î˜§
  hs: î·
  rs: ğŸ¦€
filetype:
  dir: ó°‰‹
  file: ï…› 
  socket: ó°†¨
  executable: ï’‰
  symlink-dir: ï’‚
  symlink-file: ï’
  device-char: î˜
  device-block: ó°œ«
  special: ï‹œ
